---
    version: "3.4"
    services:
      yeeter:
        build:
          context: .
        container_name: yeeter
        ports:
          - 3000:3000
        volumes:
          - .:/app
        command: ["npm", "run", "devstart"]